package net.dcn.pce.crp.policy;

import net.dcn.pce.crp.SchedulingCapacity;
import net.dcn.pce.model.*;
import net.dcn.pce.rib.LRIB;
import net.dcn.pce.rib.NRIB;

import java.util.*;

/**
 * Stage 3 (F_route): Path Selection Policy Interface.
 * Selects a preferred candidate path from routes generated by Stage 2 (F_generate).
 */
@FunctionalInterface
public interface PathSelectionPolicy {

    List<Link> selectPath(WorkloadTask task, List<List<Link>> candidateRoutes, BaseTopology topology, LRIB lrib, NRIB nrib);

    // Built-in Policy: EAP (Earliest Available Path)
    PathSelectionPolicy EAP = (task, candidateRoutes, topology, lrib, nrib) -> {
        if (candidateRoutes.isEmpty()) return Collections.emptyList();
        List<Link> earliest = earliestRoute(task, candidateRoutes, topology, lrib, false);
        // A partly used contact may carry a route only below its best-instant rate; judge routes at
        // lower rates too, but only when none fits otherwise, so every other choice is unchanged.
        return earliest.isEmpty() ? earliestRoute(task, candidateRoutes, topology, lrib, true) : earliest;
    };

    // Built-in Policy: MIN_HOP
    PathSelectionPolicy MIN_HOP = (task, candidateRoutes, topology, lrib, nrib) ->
            candidateRoutes.stream()
                           .min(Comparator.comparingInt(List::size))
                           .orElse(Collections.emptyList());

    /** Ordered Connection Criterion using deterministic contact-aware EAP evaluation. */
    PathSelectionPolicy OCC = EAP;

    /** Selects the earliest residual-feasible route generated by {@link RouteGenerationPolicy#BOUNDED_CGR}. */
    PathSelectionPolicy CGR = EAP;

    private static List<Link> earliestRoute(WorkloadTask task, List<List<Link>> candidateRoutes,
            BaseTopology topology, LRIB lrib, boolean lowerRates) {
        return candidateRoutes.stream()
                .map(route -> new AbstractMap.SimpleImmutableEntry<>(
                        route, estimateEarliestCompletion(task, route, topology, lrib, lowerRates)))
                .filter(entry -> Double.isFinite(entry.getValue()))
                .min(Comparator.comparingDouble(Map.Entry::getValue))
                .map(Map.Entry::getKey)
                .orElse(Collections.emptyList());
    }

    private static double estimateEarliestCompletion(
            WorkloadTask task, List<Link> route, BaseTopology topology, LRIB lrib, boolean lowerRates) {
        net.dcn.pce.crp.SolveDeadline.checkpoint("path selection");
        if (route.isEmpty()) {
            return Double.POSITIVE_INFINITY;
        }

        double candidateRateBps = SchedulingCapacity.minimumWholeFlowRateBps(
                task, route, topology.getRegime());
        if (!Double.isFinite(candidateRateBps) || candidateRateBps <= 0) {
            return Double.POSITIVE_INFINITY;
        }
        for (Link link : route) {
            double capacityBps = SchedulingCapacity.capacityBps(link, topology.getRegime());
            double maximumAvailableBps = lrib.getMaximumAvailableCap(
                    link.getLinkId(), capacityBps,
                    task.getOriginationTimeSec(), task.getEffectiveDeadlineSec());
            if (candidateRateBps > maximumAvailableBps + 1e-6) {
                return Double.POSITIVE_INFINITY;
            }
        }

        // Contact-scheduled routes (R_DET, and R_STOCH-with-contacts) burst at the contact line rate
        // during scheduled windows and store-and-forward between them, so completion is estimated at
        // the fastest residual rate. The slow whole-flow rate is only for continuous R_STATIC links,
        // where a flow trickles across the entire window; using it on short scheduled contacts yields
        // an impossibly long transmission that no contact can carry.
        boolean contactScheduled = topology.getRegime() == ContactRegime.R_DET
                || route.stream().anyMatch(Link::hasExplicitContactPlan);
        if (contactScheduled) {
            double fastestBps = fastestResidualRateBps(task, route, topology, lrib);
            return lowerRates
                    ? SchedulingCapacity.earliestCompletionAtSchedulableRate(
                            task, route, topology.getRegime(), lrib, fastestBps).completionSec()
                    : SchedulingCapacity.earliestCompletionSec(task, route, topology.getRegime(), lrib, fastestBps);
        }
        double atEquilibrium = SchedulingCapacity.earliestCompletionSec(
                task, route, topology.getRegime(), lrib, candidateRateBps);
        // e* stretches a transfer to exactly its deadline, so a continuous route whose next hop is
        // busy when the data arrives misses the deadline at e*. The engine then retries at the fastest
        // rate the route can carry; judge the route there too, or it is dropped before that retry.
        if (Double.isFinite(atEquilibrium)
                || !SchedulingCapacity.forwardsAsItArrives(topology.getRegime())) {
            return atEquilibrium;
        }
        return SchedulingCapacity.earliestCompletionSec(
                task, route, topology.getRegime(), lrib, fastestResidualRateBps(task, route, topology, lrib));
    }

    private static double fastestResidualRateBps(
            WorkloadTask task, List<Link> route, BaseTopology topology, LRIB lrib) {
        return route.stream()
                .mapToDouble(link -> lrib.getMaximumAvailableCap(
                        link.getLinkId(), SchedulingCapacity.capacityBps(link, topology.getRegime()),
                        task.getOriginationTimeSec(), task.getEffectiveDeadlineSec()))
                .min()
                .orElse(0.0);
    }
}
