package net.dcn.pce.pcep;

import net.dcn.pce.config.OperatorConfiguration;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.TrustManagerFactory;
import java.io.DataInputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyStore;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * PCEPS: a peer must prove who it is, not assert it.
 *
 * <p>Every prior control was something the peer could choose. A speaker entity ID is a string it
 * sends; a source address is forgeable by anyone on-path. Automatic dispatch makes the
 * consequence concrete — the controller programs paths onto "the single established session", so
 * whoever establishes one receives real LSPs.
 *
 * <p>These tests use certificates generated by `keytool` into PKCS#12 stores, so the handshake
 * exercised is a real one rather than a mocked decision about a real one.
 */
class PcepsMutualTlsTest {

    private static final char[] PASSWORD = "changeit".toCharArray();

    /** Generates a self-signed keypair in a PKCS#12 store, and exports its certificate. */
    private static void generate(Path dir, String name, String cn) throws Exception {
        generateWithDistinguishedName(dir, name, "CN=" + cn);
    }

    private static void generateWithDistinguishedName(
            Path dir, String name, String distinguishedName) throws Exception {
        run(dir, "-genkeypair", "-alias", name, "-keyalg", "RSA", "-keysize", "2048",
                "-dname", distinguishedName, "-validity", "1", "-storetype", "PKCS12",
                "-keystore", name + ".p12", "-storepass", "changeit", "-keypass", "changeit");
        run(dir, "-exportcert", "-alias", name, "-file", name + ".cer",
                "-keystore", name + ".p12", "-storepass", "changeit");
    }

    /** Builds a trust store containing the named certificates. */
    private static void trust(Path dir, String storeName, String... certificates) throws Exception {
        for (String certificate : certificates) {
            run(dir, "-importcert", "-noprompt", "-alias", certificate, "-file", certificate + ".cer",
                    "-keystore", storeName + ".p12", "-storetype", "PKCS12",
                    "-storepass", "changeit");
        }
    }

    private static void run(Path dir, String... args) throws Exception {
        java.util.List<String> command = new java.util.ArrayList<>();
        command.add(Path.of(System.getProperty("java.home"), "bin", "keytool").toString());
        command.addAll(java.util.List.of(args));
        Process process = new ProcessBuilder(command).directory(dir.toFile())
                .redirectErrorStream(true).start();
        String output = new String(process.getInputStream().readAllBytes());
        assertTrue(process.waitFor(60, TimeUnit.SECONDS), "keytool timed out");
        assertEquals(0, process.exitValue(), "keytool failed: " + output);
    }

    private static SSLContext clientContext(Path dir, String keyStore, String trustStore)
            throws Exception {
        KeyManagerFactory keys =
                KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        keys.init(load(dir.resolve(keyStore)), PASSWORD);
        TrustManagerFactory trusts =
                TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        trusts.init(load(dir.resolve(trustStore)));
        SSLContext context = SSLContext.getInstance("TLS");
        context.init(keys.getKeyManagers(), trusts.getTrustManagers(), null);
        return context;
    }

    private static KeyStore load(Path path) throws Exception {
        KeyStore store = KeyStore.getInstance("PKCS12");
        try (var in = Files.newInputStream(path)) {
            store.load(in, PASSWORD);
        }
        return store;
    }

    private static PcepSessionServer serverWithTls(Path dir) throws Exception {
        PcepTransportSecurity security = PcepTransportSecurity.fromKeyStores(
                dir.resolve("server.p12"), PASSWORD, dir.resolve("servertrust.p12"), PASSWORD);
        PcepSessionServer server = new PcepSessionServer(0, "vortex-pce", (session, report) -> { });
        server.withTransportSecurity(security);
        return server;
    }

    /** Reads the OPEN the controller sends, which only arrives if admission succeeded. */
    private static boolean receivesOpen(SSLSocket socket) {
        try {
            socket.setSoTimeout(5000);
            socket.startHandshake();
            DataInputStream in = new DataInputStream(socket.getInputStream());
            byte[] header = new byte[4];
            in.readFully(header);
            return (header[1] & 0xFF) == 1;  // OPEN
        } catch (Exception refused) {
            return false;
        }
    }

    @Test
    void aTrustedClientCertificateEstablishesASession(@TempDir Path dir) throws Exception {
        generate(dir, "server", "vortex-pce");
        generate(dir, "pcc", "pcc-alpha");
        trust(dir, "servertrust", "pcc");
        trust(dir, "pcctrust", "server");

        try (PcepSessionServer server = serverWithTls(dir)) {
            server.start("127.0.0.1");
            SSLContext client = clientContext(dir, "pcc.p12", "pcctrust.p12");
            try (SSLSocket socket = (SSLSocket) client.getSocketFactory()
                    .createSocket("127.0.0.1", server.getBoundPort())) {
                assertTrue(receivesOpen(socket),
                        "a peer with a trusted certificate should be offered a session");
            }
        }
    }

    @Test
    void anUntrustedClientCertificateIsRefused(@TempDir Path dir) throws Exception {
        // The case the address allowlist could not cover: the intruder is on loopback, exactly
        // where the real PCC is, and differs only in whose key it holds.
        generate(dir, "server", "vortex-pce");
        generate(dir, "pcc", "pcc-alpha");
        generate(dir, "intruder", "pcc-alpha");   // same subject name, different key
        trust(dir, "servertrust", "pcc");
        trust(dir, "intrudertrust", "server");

        try (PcepSessionServer server = serverWithTls(dir)) {
            server.start("127.0.0.1");
            SSLContext client = clientContext(dir, "intruder.p12", "intrudertrust.p12");
            try (SSLSocket socket = (SSLSocket) client.getSocketFactory()
                    .createSocket("127.0.0.1", server.getBoundPort())) {
                assertFalse(receivesOpen(socket),
                        "claiming the right name without the right key must not establish");
            }
            assertTrue(server.establishedSessions().isEmpty());
        }
    }

    @Test
    void theAllowlistNamesCertificateSubjectsWhenTlsIsOn(@TempDir Path dir) throws Exception {
        generate(dir, "server", "vortex-pce");
        generate(dir, "pcc", "pcc-alpha");
        trust(dir, "servertrust", "pcc");
        trust(dir, "pcctrust", "server");

        try (PcepSessionServer server = serverWithTls(dir)) {
            // A trusted certificate that is not on the allowlist: authentication succeeds and
            // authorisation does not, which are different questions.
            server.onlyAccepting(Set.of("cn=some-other-pcc"));
            server.start("127.0.0.1");
            SSLContext client = clientContext(dir, "pcc.p12", "pcctrust.p12");
            try (SSLSocket socket = (SSLSocket) client.getSocketFactory()
                    .createSocket("127.0.0.1", server.getBoundPort())) {
                assertFalse(receivesOpen(socket),
                        "a trusted but unlisted peer must still be refused");
            }

            server.onlyAccepting(Set.of("cn=pcc-alpha"));
            try (SSLSocket socket = (SSLSocket) client.getSocketFactory()
                    .createSocket("127.0.0.1", server.getBoundPort())) {
                assertTrue(receivesOpen(socket), "the listed subject should be admitted");
            }
        }
    }

    @Test
    void theGeneratedProfileSubjectIsCanonicalizedAndPermitted(@TempDir Path dir) throws Exception {
        generate(dir, "server", "vortex-pce");
        generateWithDistinguishedName(dir, "pcc",
                "CN=pcc-alpha, OU=development-only, O=VortexPCE");
        trust(dir, "servertrust", "pcc");
        trust(dir, "pcctrust", "server");

        OperatorConfiguration configuration = OperatorConfiguration.parse(Map.of(
                OperatorConfiguration.ENV_PCEP_TLS_KEYSTORE, dir.resolve("server.p12").toString(),
                OperatorConfiguration.ENV_PCEP_TLS_TRUSTSTORE,
                dir.resolve("servertrust.p12").toString(),
                OperatorConfiguration.ENV_PCEP_PERMITTED_PEERS,
                "[\"CN=pcc-alpha, OU=development-only, O=VortexPCE\"]"));

        try (PcepSessionServer server = serverWithTls(dir)) {
            server.onlyAccepting(configuration.getPcepPermittedPeers());
            server.start("127.0.0.1");
            SSLContext client = clientContext(dir, "pcc.p12", "pcctrust.p12");
            try (SSLSocket socket = (SSLSocket) client.getSocketFactory()
                    .createSocket("127.0.0.1", server.getBoundPort())) {
                assertTrue(receivesOpen(socket),
                        "the exact subject generated by the secure profile must be admitted");
            }
        }
    }

    @Test
    void tlsCannotBeEnabledAfterTheListenerStarts(@TempDir Path dir) throws Exception {
        generate(dir, "server", "vortex-pce");
        generate(dir, "pcc", "pcc-alpha");
        trust(dir, "servertrust", "pcc");

        PcepTransportSecurity security = PcepTransportSecurity.fromKeyStores(
                dir.resolve("server.p12"), PASSWORD, dir.resolve("servertrust.p12"), PASSWORD);
        try (PcepSessionServer server =
                     new PcepSessionServer(0, "vortex-pce", (session, report) -> { })) {
            server.start("127.0.0.1");
            assertThrows(IllegalStateException.class, () -> server.withTransportSecurity(security),
                    "a listener already accepting plain TCP cannot retroactively authenticate");
        }
    }
}
